### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by Windfarer** [Windfarer/mongokit-ng#1]
This project ports [mongokit](https://github.com/namlook/mongokit) to Python 3 and the latest pymongo version.

### Summary
This project can works in common Python 3 projects now, but there are some issues to be fixed.

### Environment
OS: MacOS 10.14.6 or Linux
MongoDB version: 4.0
Python 3.5~3.8

### Unit Test result:
https://travis-ci.org/Windfarer/mongokit-ng
Ran 277 tests all passed.

## TODO:
- [x] Travis CI setup
- [x] Upload to pypi
- [ ] Documentation
- [x] Fix unit tests
- [ ] Fix deprecations

## Known issues to be fixed:
- [ ] Collection.save() is deprecated. => insert_one() or replace_one()
- [ ] Collection.insert() is deprecated. => insert_one() or insert_many()
- [ ] Collection.update() is deprecated. => replace_one, update_one or update_many
- [ ] cursor.count() is deprecated. => Collection.count_documents()
- [ ] Collection.find_and_modify is deprecated, use find_one_and_delete, find_one_and_replace, or find_one_and_update instead
